# Generated by Django 5.2.8 on 2025-12-03 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LICENSE_PLATE', models.CharField(max_length=20, unique=True)),
                ('bus_type', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('duration_hours', models.FloatField(help_text='Thời gian di chuyển dự kiến')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('point_type', models.CharField(choices=[('PICKUP', 'Điểm đón'), ('DROPOFF', 'Điểm trả'), ('BOTH', 'Điểm trung chuyển (Vừa đón vừa trả)')], default='BOTH', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự điểm trên hành trình (0, 1, 2...)')),
                ('surcharge', models.DecimalField(decimal_places=0, default=0, help_text='Phụ phí nếu đón/trả tại đây (nếu có)', max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='BusBookingApp.route')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Sắp chạy'), ('RUNNING', 'Đang chạy'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Hủy')], default='SCHEDULED', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusBookingApp.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='BusBookingApp.route')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('CONFIRMED', 'Đã đặt'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('dropoff_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_bookings', to='BusBookingApp.routepoint', verbose_name='Điểm trả')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bookings', to='BusBookingApp.routepoint', verbose_name='Điểm đón')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='BusBookingApp.trip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('trip', 'seat_number'), name='unique_seat_per_trip')],
            },
        ),
    ]
